services:
  mongo: 
    image: mongo:latest
    container_name: mongo_container
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=1
      MONGO_INITDB_ROOT_USERNAME: admin_user 
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backendNetwork

  backend:
    image: backend_productos
    container_name: backend_container
    volumes:
      - ./backend:/app
    ports:
      - "8089:8000"
    networks:
      - backendNetwork

volumes:
  mongo_data:
    name: web3_mongo_compass_data_20260923
    external: true
  backend:
    external: true

networks:
  backendNetwork:
    driver: bridge
