services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: jon
      MONGO_INITDB_ROOT_PASSWORD: jon
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
    - backend_network
  backend_code:
    image: backend_productos
    container_name: backend_container
    volumes:
      - ./backend:/app
    ports: 
    - "8089:8000"
    networks:
    - backend_network
volumes:
  mongo_data:
    external: true
  backend_code:
    external: true
networks:
  backend_network:
    driver: bridge