# Imagen base ligera de Python
FROM python:3.13-slim

# Creamos directorio de trabajo
WORKDIR /app

# Copiamos los archivos de dependencias (viven en la raíz del repo)
COPY pyproject.toml poetry.lock ./

# Copiamos el código de la app
COPY backend/main.py ./main.py

# Exponer el puerto donde correra la app
EXPOSE 8000

# instalamos poetry
RUN pip install --no-cache-dir "poetry"

RUN poetry install --no-root --only main --no-cache

# por ultimo definimos el comando para correr la aplicacion
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

