[tool.poetry]
name = "backend-productos"
version = "0.1.0"
description = "FastAPI backend for productos with MongoDB"
authors = ["Santiago Ortega"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.141.1"
uvicorn = "^0.52.4"
pymongo = "^4.17.0"
prometheus-fastapi-instrumentator = "^7.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
build-backend = "poetry.core.masonry.api"
